# Generated by Django 5.0.4 on 2024-04-24 07:48

import przegladarkaobrazkow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SVGImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(default=przegladarkaobrazkow.models.default_svg_content)),
                ('name', models.CharField(max_length=100)),
                ('width', models.IntegerField(validators=[przegladarkaobrazkow.models.validate_positive])),
                ('height', models.IntegerField(validators=[przegladarkaobrazkow.models.validate_positive])),
            ],
        ),
    ]
