# Generated by Django 5.0.4 on 2024-04-24 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przegladarkaobrazkow', '0002_alter_svgimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='svgimage',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editable_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
